[project]
name = "pointlist"
version = "1.0.0"
description = "PointList"
requires-python = ">=3.13"

dependencies = [
    "flet==0.28.3",
    "python-dotenv",
    "supabase>=2.0.0",
    "pg8000>=1.30.0",
    "openai>=1.0.0",
    "packaging",
    "scramp",
    "requests",
    "python-dateutil"
]

[tool.flet]
org = "com.pointlist"
product = "PointList"

[tool.flet.app]
path = "."